// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBTPipVeZIduQKNGB1hbDFnQQdLtIj2E',
    appId: '1:1033251430272:web:c4395c97d76b1275f7ab65',
    messagingSenderId: '1033251430272',
    projectId: 'pictures-com-pk',
    authDomain: 'pictures-com-pk.firebaseapp.com',
    storageBucket: 'pictures-com-pk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OY6sX6uK61KslFsFTwD3Oj0RlRiw-kE',
    appId: '1:1033251430272:android:8522f6bf209ebf3bf7ab65',
    messagingSenderId: '1033251430272',
    projectId: 'pictures-com-pk',
    storageBucket: 'pictures-com-pk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMi6-AM6e3xYeSQiUR2GDxgqgNY5C-6gs',
    appId: '1:1033251430272:ios:edf519a2cbccfdd1f7ab65',
    messagingSenderId: '1033251430272',
    projectId: 'pictures-com-pk',
    storageBucket: 'pictures-com-pk.appspot.com',
    iosBundleId: 'com.example.picturesDotCom',
  );
}
